global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'MySpringApp'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ '192.168.100.102:8080' ]